---
- name: Set Docker
  import_tasks: prepare.yml

- name: Check if docker is installed
  stat: path="/usr/bin/docker"
  register: docker_check

- name: Check Version if docker is installed
  command: "docker version -f '{{ '{{' }}.Client.Version{{ '}}' }}'"
  register: get_docker_version
  ignore_errors: true
  when: docker_check.stat.isreg is defined

- name: minimum docker version if docker is installed
  fail:
    msg: >
          docker requires a minimum version of
          {{ docker_min_version }} on
          {{ ansible_distribution }}-{{ ansible_distribution_version }}
  when: docker_check.stat.isreg is defined and get_docker_version.stdout is version(docker_min_version, "<")

- name: Ensure docker service is started and enabled
  service:
    name: docker
    enabled: yes
    state: started
  ignore_errors: true

