- name: Docker | Install docker online
  shell: "export VERSION=18.06 && curl -fsSL http://rainbond-pkg.oss-cn-shanghai.aliyuncs.com/releases/docker/install-docker.sh | bash -s docker "
  register: docker_task_result
  until: docker_task_result is succeeded
  retries: 4
  notify: restart docker

- name: Docker | Start docker
  service:
    name: docker
    enabled: yes
    state: started
