---

- name: View master-master replication status
  shell: docker exec -t rbd-db sh -c "mysql -e 'show slave status\G;'| grep -E 'Slave_IO_Running|Slave_SQL_Running'|awk '{print $2}'|grep  Yes"
  register: return_value

- name: View db cluster status
  debug: var=return_value.stdout_lines verbosity=0
  failed_when: ' "No" in return_value.stdout'
