--- 
- name: Downloads mysql image
  shell: docker pull 16601306786/rbd-db:v5.7.26 && mkdir -p /opt/rainbond/mysql
 
- name: DB | Copy DB conf
  template:
    src: mysqld.cnf.j2
    dest: "/opt/rainbond/mysql/mysqld.cnf"

- name: DB | Copy DB service
  template:
    src: rbd-db.service.j2
    dest: "/etc/systemd/system/rbd-db.service"

- name: start_mysql_service
  shell: systemctl start rbd-db    
