--- 
- name: Downloads mysql image
  shell: docker pull 16601306786/rbd-db:v5.7.26

- name: init_mysql
  shell: docker run --name rbd-db --network host -e MYSQL_ALLOW_EMPTY_PASSWORD="yes" -v /opt/rainbond/data/mysql:/data -i 16601306786/rbd-db:v5.7.26 && sleep 30
  tags: 
    - init_mysql
    
 
- name: get_mysql_passwd
  shell: cat log/mysqld.log |grep localhost|awk -F ':' '{print $4}'|cut -c  2-
  register: mysql_init_passwd
  args:  
    chdir: "{{ mysql_install_path }}/{{ mysql_link }}"
  tags: 
    - get_mysql_passwd
 
 
 
- name: dispaly_passwd
  debug: 
    msg: "{{ mysql_init_passwd.stdout }}"
  tags:
    - dispaly_passwd
 
 
 
- name: copy_mysql.server
  copy:
    src: "{{ mysql_install_path }}/{{ mysql_link }}/support-files/mysql.server"
    dest: /etc/init.d/mysql-{{ mysql_port }}.server
    mode: 0755
  tags:
     - copy_mysql.server
 
 
 
- name: add_mysql_systemd
  template:
    src: mysql.service.j2
    dest: /etc/systemd/system/mysql-{{ mysql_port }}.service
  tags:
    - add_mysql_systemd
 
 
 
- name: start_mysql_service
  systemd:
    name: mysql-{{ mysql_port }}
    daemon_reload: yes
    enabled: yes
    state: restarted
  tags:
    - start_mysql_service
 
 
 
- name: alter_passwd
  shell: ./bin/mysqladmin -u root -p'{{mysql_init_passwd.stdout}}' password '{{ mysql_root_passwd }}'
  args:
    chdir: "{{ mysql_install_path }}/{{ mysql_link }}"
  tags:
    - alter_passwd
