--- 
- name: The next task may take some time to execute
  debug:
    msg: "The next task may take some time to execute: download rbd-db image"

- name: Downloads mysql image
  shell: docker pull 16601306786/rbd-db:v5.7.26  && mkdir -p /opt/rainbond/etc/mysql
 
- name: DB | Copy DB conf
  template:
    src: master.cnf.j2
    dest: "/opt/rainbond/etc/mysql/mysqld.cnf"
  when: inventory_hostname in groups['new-master']

- name: DB | Copy DB conf
  template:
    src: slave.cnf.j2
    dest: "/opt/rainbond/etc/mysql/mysqld.cnf"
  when: inventory_hostname in groups['new-slave']

- name: DB | Copy DB service
  template:
    src: rbd-db.service.j2
    dest: "/etc/systemd/system/rbd-db.service"
    mode: 755

- name: Check whether MySQL data directory exists
  stat: path="/opt/rainbond/data/mysql"
  register: mysql_data_check

- name: Remove database data directory
  shell: rm -rf  /opt/rainbond/data/mysql.bak && mv /opt/rainbond/data/mysql  /opt/rainbond/data/mysql.bak
  when: mysql_data_check.stat.isreg is defined

- name: Remove container
  docker_container:
    name: rbd-db
    state: absent

- name: Start rbd-db
  service:
    name: rbd-db
    enabled: yes
    state: started

