--- 
- name: Downloads mysql image
  shell: docker pull 16601306786/rbd-db:v5.7.26 && mkdir -p /opt/rainbond/mysql
 
- name: DB | Copy DB conf
  template:
    src: mysqld.cnf.j2
    dest: "/opt/rainbond/mysql/mysqld.cnf"

- name: DB | Copy DB service
  template:
    src: rbd-db.service.j2
    dest: "/etc/systemd/system/rbd-db.service"
    mode: 755

- name: Check whether MySQL data directory exists
  stat: path="/opt/rainbond/data/mysql"
  register: mysql_data_check

- name: Remove database data directory
  shell: rm -rf  /opt/rainbond/data/mysql.bak && mv /opt/rainbond/data/mysql  /opt/rainbond/data/mysql.bak
  when: mysql_data_check.stat.isreg is defined

- name: Delete container in exit state
  shell: docker rm rbd-db -f
  ignore_errors: yes

- name: start_mysql_service
  shell: systemctl start rbd-db
