---
- name: Prepare db
  import_tasks: prepare_db.yml

- name: Add Slave
  import_tasks: add-slave.yml

- name: Add Slave to Master
  import_tasks: add-master.yml

- name: Check status
  import_tasks: check.yml
