--- 
- name: The next task may take some time to execute
  debug:
    msg: "The next task may take some time to execute: Install Keepalived"

- name: Install Keepalived
  yum: 
    name: 
      - keepalived
      - iproute
    state: present
when: ansible_distribution == "CentOS"

- name: Install  Keepalived
  apt: 
    name:
      - keepalived
    update_cache: yes
    autoclean: yes
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Start the keepalived service
  systemd:
    name: keepalived
    state: started
    enabled: True

- name: Copy keepalived conf
  template:
    src: master.conf.j2
    dest: "/etc/keepalived/keepalived.conf"
  when: inventory_hostname in groups['new-master']

- name: Copy DB conf
  template:
    src: slave.conf.j2
    dest: "/etc/keepalived/keepalived.conf"
  when: inventory_hostname in groups['new-slave']

- name: Copy check script
  template:
    src: check_mysql.sh.j2
    dest: "/etc/keepalived/check_mysql.sh"
    mode: 755

- name: Copy Keepalived service
  template:
    src: keepalived.service.j2
    dest: "/usr/lib/systemd/system/keepalived.service"

- name: daemon-reload to pick up config changes and restart service
  systemd:
    state: restarted
    daemon_reload: yes
    name: keepalived
