---
- name: Stop if ansible version is too low
  assert:
    that:
      - ansible_version.full|version_compare('2.3.0', '>=')
  when: inventory_hostname in groups['new-master']

- name: Stop if unknown OS
  assert:
    that: ansible_distribution in [ 'CentOS','Ubuntu']
  ignore_errors: false

- name: prepare |Disable selinux
  shell: "setenforce 0"
  failed_when: false
  when: ansible_distribution == "CentOS"

- name: prepare |Disable selinux forever
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"
  when: ansible_distribution == "CentOS"

- name: prepare |Remove centos firewall pkg
  yum:
    name:
      - firewalld
      - python-firewall
      - firewalld-filesystem
    state: absent
  when: ansible_distribution == "CentOS"


- name: prepare |Install ubuntu package
  apt: 
    name:
      - curl
      - net-tools
      - sshpass 
      - python-pip  
      - net-tools
    update_cache: yes
    autoclean: yes
    state: present
  when: ansible_distribution == "Ubuntu"

